"use client"

import { useState, useTransition } from "react"
import { useRouter } from "next/navigation"
import { useTranslations } from "next-intl"
import { toast } from "sonner"
import { Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { createAsset, searchOrderLinesForAssetCreation } from "@/lib/actions/assets"
import { translateActionError } from "@/lib/i18n/action-errors"

type LineOption = Awaited<ReturnType<typeof searchOrderLinesForAssetCreation>>[number]

export function CreateAssetForm() {
  const t = useTranslations("assets")
  const router = useRouter()
  const [query, setQuery] = useState("")
  const [options, setOptions] = useState<LineOption[]>([])
  const [selected, setSelected] = useState<LineOption | null>(null)
  const [serialNumber, setSerialNumber] = useState("")
  const [assetTag, setAssetTag] = useState("")
  const [searching, setSearching] = useState(false)
  const [pending, startTransition] = useTransition()

  async function handleSearch(value: string) {
    setQuery(value)
    setSelected(null)
    if (!value.trim()) {
      setOptions([])
      return
    }
    setSearching(true)
    const results = await searchOrderLinesForAssetCreation(value)
    setSearching(false)
    setOptions(results)
  }

  function handleSubmit() {
    if (!selected || !serialNumber.trim()) return
    startTransition(async () => {
      const result = await createAsset({
        orderLineId: selected.orderLineId,
        serialNumber: serialNumber.trim(),
        assetTag: assetTag.trim() || undefined,
      })
      if (result.error) {
        toast.error(translateActionError(result.error))
        return
      }
      toast.success(t("assetCreated"))
      router.push(`/admin/assets/${result.id}`)
    })
  }

  return (
    <div className="space-y-4 rounded-lg border p-4">
      <div>
        <label className="mb-1 block text-sm font-medium">{t("selectSourceLine")}</label>
        <input
          value={query}
          onChange={(e) => handleSearch(e.target.value)}
          placeholder={t("selectSourceLinePlaceholder")}
          className="flex h-9 w-full rounded-lg border border-input bg-background px-3 text-sm focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50 focus-visible:border-ring"
        />
        {searching && <p className="mt-1 text-xs text-muted-foreground">{t("searching")}</p>}
        {options.length > 0 && !selected && (
          <ul className="mt-1 max-h-48 overflow-y-auto rounded-lg border">
            {options.map((o) => (
              <li key={o.orderLineId}>
                <button
                  type="button"
                  onClick={() => {
                    setSelected(o)
                    setQuery(`${o.orderNumber} · ${[o.brand, o.model, o.description].filter(Boolean).join(" ")}`)
                    setOptions([])
                  }}
                  className="w-full px-3 py-2 text-start text-sm hover:bg-accent"
                >
                  <span className="font-mono text-xs text-kara-purple" dir="ltr">{o.orderNumber}</span>{" "}
                  {[o.brand, o.model, o.description].filter(Boolean).join(" · ")}
                </button>
              </li>
            ))}
          </ul>
        )}
      </div>

      <div>
        <label className="mb-1 block text-sm font-medium">{t("serial")}</label>
        <input
          value={serialNumber}
          onChange={(e) => setSerialNumber(e.target.value)}
          placeholder={t("scanSerialPlaceholder")}
          dir="ltr"
          className="flex h-9 w-full rounded-lg border border-input bg-background px-3 text-sm focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50 focus-visible:border-ring"
        />
      </div>

      <div>
        <label className="mb-1 block text-sm font-medium">
          {t("assetTag")} <span className="text-xs text-muted-foreground">({t("optionalAutoGenerated")})</span>
        </label>
        <input
          value={assetTag}
          onChange={(e) => setAssetTag(e.target.value)}
          placeholder="KARA-00001"
          dir="ltr"
          className="flex h-9 w-full rounded-lg border border-input bg-background px-3 text-sm focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50 focus-visible:border-ring"
        />
      </div>

      <Button
        onClick={handleSubmit}
        disabled={pending || !selected || !serialNumber.trim()}
        className="w-full sm:w-auto"
      >
        {pending && <Loader2 className="me-2 size-4 animate-spin" />}
        {t("createAsset")}
      </Button>
    </div>
  )
}
